language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.10.0

script:
  - cargo build --verbose
  - cargo build --examples --verbose
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --verbose; fi
