language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.10.0

script:
  - cargo build --verbose
  - if [ "$TRAVIS_RUST_VERSION" != "1.10.0" ]; then cargo build --example demo --verbose; fi
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo test --verbose; fi
